curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/3d_rollball_objects_cv.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/3d_rollball_objects_v2.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/BrokenJigsawbrokenjigsaw_swap.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/card.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/cardistance.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/conveyor.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/coordinatesmatch.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/coordinatesmatch_cv.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/counting.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/dicematch.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/dice_pair.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/frankenhead.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/hand_number_puzzle.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/hopscotch_highsec.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/knotsCrossesCircle.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/penguin.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/penguins-icon.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/penguins.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/rockstack.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/rockstack_v2.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/shadows.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/train_coordinates.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/train_coordinates_cv.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/unbentobjects.onnx
curl -o /app/funcaptcha_challenger https://github.com/yufeiyohi/funcaptcha-api/releases/download/model/version.json